# Generated by Django 6.0.2 on 2026-03-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
